[build]
builder = "nixpacks"
buildCommand = "yarn install && yarn build"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["nodejs_20"]

[deploy]
startCommand = "yarn start:prod"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
