export enum TypeSubject {
  branch = "sucursales",
  permission = "permisos",
  role = "roles",
  user = "usuarios",
  staff = "staffs",
  tutor = "tutores",
  teacher = "profesores",
  student = "estudiantes",
  assignmentRoom = "asignación de aulas",
  assignmentSchedule = "asignación de horarios",
  booking = "reservas",
  room = "aulas",
  specialty = "especialidades",
  schedule = "horarios",
  inscription = "incripciones",
  payment = "pagos",
  invoice = "facturas",
  refund = "devoluciones",
  price = "precios",
  report = "reportes",
  debt = "deudas",
  attendance = 'asistencias',
  correspondence = 'correspondencias',
}